### ISSUE TITLE
バージョン管理 FVMを実装する。

### ISSUE THREAD

**Issue by TakeRai** [Team-PastQuiz11/PastQuiz#17]
https://zenn.dev/altiveinc/articles/flutter-version-management

こちらの記事などを参考にして実装する。

**Comment by TakeRai** [comment]
他メンバーの導入方法だけちゃんと書きます！

**Comment by manojunichiro** [comment]
fvmは導入していなかったのですが、複数プロジェクトに携わる場合は便利（必須？）とのことでインストールしました。
```
dart pub global activate fvm
fvm --version
}
```
ひとまず上記でfvmのインストールは成功し、アプリも正常に起動しました。
* インストール前の当方手元のflutterバージョンはTakeRaiさんと同じ3.3.10でした。

**Comment by manojunichiro** [comment]
- developにマージしたので、以降の作業はdevelopに移動(checkout)してからfeature/ブランチを切るようにしてください。

**Comment by TakeRai** [comment]
mainにマージしました。
