### ISSUE TITLE
[Future task] [画面設計・実装] 問題文表示用の上部画面作成

### ISSUE THREAD

**Issue by k-saito-en** [Team-PastQuiz11/PastQuiz#19]
# 現状

- 問題表示画面にて、問題文が長文で表示されることが想定されるが、スクロール表示が実装されていない。

# 実現したいこと

- 問題文の長さによって動的にスクロール表示されるWidgetを実装したい

- ただし、画面下部には解答選択肢を表示する予定なので、スクロールWidgetは画面上半分のみの実装をお願いしたいです

![スクリーンショット 2023-01-11 6 17 07](https://user-images.githubusercontent.com/111550856/211983229-782b6dc2-dd88-4ebb-92db-6d796e3f6f41.png)

# 備考

- [画面設計図](https://www.figma.com/file/SNmS6QbI50v8Z0cZQlKH0Z/無題?node-id=0%3A1)

- 提案者　アサノさん

**Comment by tora-muscle** [comment]
@TakeRai
こちら、画面のUIカラーは添付画像のような「オレンジとクリーム色を基調としたもの」ということで宜しいでしょうか？

**Comment by TakeRai** [comment]
@k-saito-en 

色のようなUIに直結する部分については、後付けでも実装しやすいと考えております。そのため、デザイン面について確定していることはほとんどないです🙇 

イメージとして、以下の色合いで実装するのはどうだろうと練っているくらいです。
ーーー
肌色 FFFBF6
ブラウン 663c00
オレンジ ff9500

肌色 6 ~ 7
オレンジ 2~3
ブラウン　1未満
ーーー

確定事項ではないので、後々変わることを予想しております。

**Comment by TakeRai** [comment]
@k-saito-en 

アサノさんの案を基本として実装するつもりです。

以上の画像にあるようなデザインは、アサノさんの案を見る前の構想なので破棄するくらいの気持ちで考えてもらって問題ないです。以上の画像も、選択肢のボタンの部分のデザインを練る上でfigmaを使って試行錯誤した過程です。まだまだ完成でないと思っていただけると助かります。

**Comment by TakeRai** [comment]
@k-saito-en 

今回のプロジェクトにおいて、ユーザーが必要だと思われる要件を実装するのがまず第一だと考えています。
具体的にはアサノさんの案、チャット画面、その他それに付随する実装。

その要件は現状ある程度固まっており、それを踏まえて最低限の実装は進められると私は考えています。具体的な色合いのようなUI・フロントの部分に関しては、アプリ全体の設計等に直結するものとは考えていません。そのためfigmaのようなデザイン実装は後回しになっています。

これが今の私の認識です🙇‍♀️

**Comment by tora-muscle** [comment]
@TakeRai 
承知いたしました！
ご回答ありがとうございます。

**画面上部のスクロール機能の実装**　のみ進めてまいります！

**Comment by TakeRai** [comment]
２画面分けのUIUXで参考になりそうなものがあれば共有しようと思っています。UIポケットなど見ます。

**Comment by tora-muscle** [comment]
@TakeRai 

> 問題文の長さによって動的にスクロール表示されるWidgetを実装したい
> 
> ただし、画面下部には解答選択肢を表示する予定なので、スクロールWidgetは画面上半分のみの実装をお願いしたいです

こちら、実装完了致しました。

**画面スクロール実装エビデンス動画▼**
https://user-images.githubusercontent.com/111550856/212527277-3b425632-7dc7-4f9e-b96a-32267ebdf156.mov


**実装結果▼**
![issue#19_widget構成](https://user-images.githubusercontent.com/111550856/212527313-5078f486-df0b-4baf-ba1d-d134289e8fb3.png)

**検証環境▼**
Pixel 6 API33
Android Tiramisu Google APIs | arm64

**備考▼**
画面上下の２分割のwidget構成に伴い、`正解・不正解表示`を`画面下部のExpanded`に取り込み、選択肢下の表示に変更となっております。
![issue#19_正誤表示変更後](https://user-images.githubusercontent.com/111550856/212527566-e0075b4b-f99e-4ea6-a694-1b0aced3023a.png)
