### ISSUE TITLE
issue-create-test: Android Studio not insalled 

### ISSUE THREAD

**Issue by asakura-wasabi** [Team-PastQuiz11/PastQuiz#2]
※issue作成テストと、自身の問題解決に使用しています※

VScodeを使用したFlutter環境構築時に、コマンドプロンプトに
[!]Android Studio (not installed) と表示される。

**Comment by TakeRai** [comment]
https://kiyosan.life/2021/06/04/flutter/

 こちらの記事の内容で確認して見てください！

**Comment by asakura-wasabi** [comment]
ありがとうございます！
無事コマンドプロンプト内の！が消えてレ点のみになりました。
