### ISSUE TITLE
✨ 問題画面の実装・修正

### ISSUE THREAD

**Issue by tora-muscle** [Team-PastQuiz11/PastQuiz#29]
# 現状

#19 にて、問題画面の問題文スクロール表示部分を作成。

# 実現したいこと

- [x] 問題文スクロール表示とは別に、画面下半分（添付画像参照）の「解答選択肢表示」の部分の実装をお願いします。

![211983229-782b6dc2-dd88-4ebb-92db-6d796e3f6f41](https://user-images.githubusercontent.com/111550856/212831734-6de189f4-ae52-4d04-82e0-e5834008bed3.png)

# 備考

- [画面設計図](https://www.figma.com/file/SNmS6QbI50v8Z0cZQlKH0Z/無題?node-id=0%3A1)
- 提案者　アサノさん
- [jira課題](https://pastquiz11.atlassian.net/browse/LU11-35)

**Comment by TakeRai** [comment]
Issue立てありがとうございます。

**Comment by tora-muscle** [comment]
メモ
@TakeRai さんのレビュー待ち

**Comment by tora-muscle** [comment]
@TakeRai 
レビュー済みということで本課題はクローズ致します。

ご対応ありがとうございます！

**Comment by manojunichiro** [comment]
このイメージで実装していきます！

**Comment by TakeRai** [comment]
@manojunichiro 

ありがとうございます！
