### ISSUE TITLE
SSH化設定中に「Please make sure you have the correct access rights and the repository exists.」と出てくる。

### ISSUE THREAD

**Issue by asakura-wasabi** [Team-PastQuiz11/PastQuiz#3]
windows10環境でSSH形式のgit cloneを実施する為、SSH環境を設定する際に
https://kenjimorita.jp/please-make-sure-you-have-the-correct-access-rights-and-the-repository-exists/
上記サイトを参考に設定を進めていたところ、
表題2.Comfirm your created ssh key
の No such file or directoryが出ず、
'ls' is not recognized as an internal or external command,
operable program or batch file.とコマンドプロンプトに表示され、進まない。

**Comment by TakeRai** [comment]
https://algorithm.joho.info/programming/batch/ls-dir-command/

上記ブログによれば、lsコマンドがdirコマンドに該当するため
dirコマンドでの実行をお試しください。
